name: Check on PR

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: go build -v ./...
      - name: Integration tests
        run: go test -timeout 30s -v -tags=integration -coverprofile=coverage.out -coverpkg=./... ./...
